apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    konghq.com/protocols: https
    # Remove legacy annotation if you're using ingressClassName
    # kubernetes.io/ingress.class: kong
  labels:
    app.kubernetes.io/name: argocd-server
spec:
  ingressClassName: kong
  tls:
  - hosts:
    - argo-stage.parkplus.io
    secretName: argo-stage-tls # <-- make sure this secret exists
  rules:
  - host: argo-stage.parkplus.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 443
